export const IVY_COLORS = {
  purple: "#5C3DF5",
  purpleLight: "#9987F5",
  green: "#12B880",
  greenLight: "#5AE0B4",
  red: "#F53D3D",
  redLight: "#F5AB87",
  blue: "#3193F5",
  blueLight: "#87BEF5",
  yellow: "#F5D018",
  yellowLight: "#F5E287",
  orange: "#F57A3D",
  orangeLight: "#F5AB87",
  pink: "#F53D99",
  pinkLight: "#F587BE",
  teal: "#10A372",
  indigo: "#4D33CC",
  gray: "#74747A",
  darkGray: "#303033",
  extraDarkGray: "#1C1C1F",
  black: "#09090A",
  trueBlack: "#000000",
  white: "#FAFAFC",
};

export const COLOR_OPTIONS = [
  { name: "Purple", value: "#5C3DF5" },
  { name: "Green", value: "#12B880" },
  { name: "Blue", value: "#3193F5" },
  { name: "Red", value: "#F53D3D" },
  { name: "Yellow", value: "#F5D018" },
  { name: "Orange", value: "#F57A3D" },
  { name: "Pink", value: "#F53D99" },
  { name: "Teal", value: "#10A372" },
  { name: "Indigo", value: "#4D33CC" },
  { name: "Cyan", value: "#00B4D8" },
  { name: "Amber", value: "#D97706" },
  { name: "Rose", value: "#E11D48" },
];

export const CURRENCY_LIST = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
];

export const DEFAULT_CATEGORIES = [
  { name: "Food & Drinks", color: "#F57A3D", icon: "utensils" },
  { name: "Groceries", color: "#12B880", icon: "shopping-cart" },
  { name: "Shopping", color: "#F53D99", icon: "shopping-bag" },
  { name: "Transportation", color: "#3193F5", icon: "car" },
  { name: "Housing & Bills", color: "#5C3DF5", icon: "home" },
  { name: "Entertainment", color: "#F5D018", icon: "gamepad-2" },
  { name: "Health & Fitness", color: "#10A372", icon: "heart-pulse" },
  { name: "Education", color: "#4D33CC", icon: "graduation-cap" },
  { name: "Salary", color: "#12B880", icon: "briefcase" },
  { name: "Investments", color: "#3193F5", icon: "trending-up" },
  { name: "Gifts & Donations", color: "#E11D48", icon: "gift" },
  { name: "Other", color: "#74747A", icon: "circle-dot" },
];

export const DEFAULT_ACCOUNTS = [
  { name: "Cash", currency: "USD", color: "#12B880", icon: "banknote", includeInBalance: true },
  { name: "Bank Account", currency: "USD", color: "#3193F5", icon: "landmark", includeInBalance: true },
  { name: "Savings", currency: "USD", color: "#5C3DF5", icon: "piggy-bank", includeInBalance: true },
  { name: "Credit Card", currency: "USD", color: "#F53D3D", icon: "credit-card", includeInBalance: true },
];

export const ICON_OPTIONS = [
  "wallet",
  "banknote",
  "landmark",
  "credit-card",
  "piggy-bank",
  "coins",
  "utensils",
  "shopping-cart",
  "shopping-bag",
  "car",
  "home",
  "gamepad-2",
  "heart-pulse",
  "graduation-cap",
  "briefcase",
  "trending-up",
  "gift",
  "coffee",
  "fuel",
  "plane",
  "smartphone",
  "tv",
  "receipt",
  "dumbbell",
  "music",
  "shield",
  "tag",
  "circle-dot",
];
