import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        ivy: {
          white: "#FAFAFC",
          extraLightGray: "#EBEBF0",
          lightGray: "#CBCBD6",
          gray: "#74747A",
          darkGray: "#303033",
          extraDarkGray: "#1C1C1F",
          black: "#09090A",
          trueBlack: "#000000",
          purple: {
            DEFAULT: "#5C3DF5",
            primary: "#5C3DF5",
            extraLight: "#B8ABF5",
            light: "#9987F5",
            kindaLight: "#7B62F5",
            kindaDark: "#4D33CC",
            dark: "#36248F",
            extraDark: "#1F1452",
          },
          green: {
            DEFAULT: "#12B880",
            primary: "#12B880",
            extraLight: "#ABF5DC",
            light: "#5AE0B4",
            kindaLight: "#38E0A8",
            kindaDark: "#10A372",
            dark: "#0C7A56",
            extraDark: "#085239",
          },
          red: {
            DEFAULT: "#F53D3D",
            primary: "#F53D3D",
            extraLight: "#F5ABAB",
            light: "#F5AB87",
            kindaLight: "#F56262",
            kindaDark: "#CC3333",
            dark: "#8F2424",
            extraDark: "#521414",
          },
          blue: {
            DEFAULT: "#3193F5",
            primary: "#3193F5",
            extraLight: "#ABD0F5",
            light: "#87BEF5",
            kindaLight: "#62ABF5",
            kindaDark: "#3380CC",
            dark: "#24598F",
            extraDark: "#153352",
          },
          yellow: {
            DEFAULT: "#F5D018",
            primary: "#F5D018",
            extraLight: "#F5E9AB",
            light: "#F5E287",
            kindaLight: "#F5DC62",
            kindaDark: "#CCAD14",
            dark: "#A38B10",
            extraDark: "#7A680C",
          },
          orange: {
            DEFAULT: "#F57A3D",
            primary: "#F57A3D",
            extraLight: "#F5C4AB",
            light: "#F5AB87",
            kindaLight: "#F59362",
            kindaDark: "#CC6633",
            dark: "#8F4724",
            extraDark: "#522914",
          },
          pink: {
            DEFAULT: "#F53D99",
            primary: "#F53D99",
            extraLight: "#F5ABD0",
            light: "#F587BE",
            kindaLight: "#F562AB",
            kindaDark: "#CC3380",
            dark: "#8F2459",
            extraDark: "#521433",
          },
        },
      },
      borderRadius: {
        "ivy-sm": "12px",
        "ivy-md": "18px",
        "ivy-lg": "24px",
        "ivy-xl": "32px",
        "ivy-full": "9999px",
      },
      boxShadow: {
        "ivy-card": "0 8px 30px rgba(0, 0, 0, 0.06)",
        "ivy-glow": "0 0 25px rgba(92, 61, 245, 0.25)",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
