export const IVY_COLORS = {
  purple: "#5C3DF5",
  purpleLight: "#7962F7",
  green: "#12B880",
  red: "#F53D3D",
  blue: "#3193F5",
  yellow: "#F5D018",
  orange: "#F57A3D",
  pink: "#F53D7A",
  teal: "#3DF5CA",
  cyan: "#3DD7F5",
  indigo: "#3D4BF5",
  violet: "#933DF5",
  dark: "#09090A",
  darkGray: "#1C1C1F",
  lightGray: "#28282C",
};

export const COLOR_OPTIONS = [
  { name: "Ivy Purple", value: "#5C3DF5" },
  { name: "Ivy Green", value: "#12B880" },
  { name: "Ivy Red", value: "#F53D3D" },
  { name: "Ivy Blue", value: "#3193F5" },
  { name: "Ivy Yellow", value: "#F5D018" },
  { name: "Ivy Orange", value: "#F57A3D" },
  { name: "Ivy Pink", value: "#F53D7A" },
  { name: "Ivy Teal", value: "#3DF5CA" },
  { name: "Ivy Violet", value: "#933DF5" },
  { name: "Ivy Cyan", value: "#3DD7F5" },
];

export const ICON_OPTIONS = [
  "wallet",
  "credit-card",
  "piggy-bank",
  "landmark",
  "coins",
  "banknote",
  "utensils",
  "shopping-cart",
  "shopping-bag",
  "car",
  "home",
  "gamepad-2",
  "heart-pulse",
  "graduation-cap",
  "trending-up",
  "zap",
  "smile",
  "coffee",
  "plane",
  "gift",
  "film",
  "smartphone",
  "music",
  "book",
  "tag",
  "hand-coins",
  "dollar-sign",
  "badge-percent",
  "circle-dot",
];

export const CURRENCY_LIST = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "CAD", symbol: "CA$", name: "Canadian Dollar" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
];
